### ISSUE TITLE
Authentication failing some n times before working

### ISSUE THREAD

**Issue by Fclem** [philippelt/lhubic#1]
```python
Authorization code (user) request failure : 'location'
Traceback (most recent call last):
  File "/home/clem/tmp/lhubic/lhubic.py", line 128, in auth
    location = urlparse(r.headers['location'])
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 170, in <module>
    my_hubic = HubicClient()
  File "./main.py", line 18, in __init__
    if self._auth():
  File "./main.py", line 89, in _auth
    self.hubic.os_auth() # To get an openstack swift token
  File "/home/clem/tmp/lhubic/lhubic.py", line 71, in os_auth
    self.auth()
  File "/home/clem/tmp/lhubic/lhubic.py", line 133, in auth
    raise HubicAuthFailure("Failed to request authorization code, check user/password")
lhubic.HubicAuthFailure: Failed to request authorization code, check user/password
```

This is the error I get some random amount of time, before authentication actually work with no changes to code nor credentials.
Last time I tried, it failed with this error 11 times in a row before it worked.
Then I get the auth_token, which prevents this issue from occurring again.

**Comment by philippelt** [comment]
I have noticed from time to time that the Hubic authentication request fail mostly in two scenarios :  

1. an http status code of 200 but no body part where to find token and other data
2. no response which lead to timeout

In the recent days, it seems to be less frequent. In my transfert utility, I implemented a timeout and 3 retry to avoid the problem.

I also done some work on the lhubic library, are you using the very last version ?

**Comment by Fclem** [comment]
Yes I just cloned this repo yesterday, so I guess I must have the last version.

**Comment by Fclem** [comment]
So after some more digging, it seems that Hubic limit authentication request to one per 3-4 minutes.
If not using the given refresh token within this time, and attempting auth retry the server returns HTTP509 `auth: Access grant : 509`.

I thus edited the code to raise `HubicAccessFailure` when that happens as this happen even when credentials are correct.
